/* This file was generated by syncqt. */
#ifndef QT_QTJSONRPC_VERSION_H
#define QT_QTJSONRPC_VERSION_H

#define QTJSONRPC_VERSION_STR "6.4.1"

#define QTJSONRPC_VERSION 0x060401

#endif // QT_QTJSONRPC_VERSION_H
