/* This file was generated by syncqt. */
#ifndef QT_QT3DCORE_VERSION_H
#define QT_QT3DCORE_VERSION_H

#define QT3DCORE_VERSION_STR "5.15.5"

#define QT3DCORE_VERSION 0x050F05

#endif // QT_QT3DCORE_VERSION_H
